### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by yukimasano** [princetonvisualai/imagenet-face-obfuscation#2]
Hi, thanks for the great paper and the repo! Would you be able to provide links to the blur-trained ResNets? Thanks!

**Comment by yangky11** [comment]
Hi,

That's on our TODO list and I'll post an update here when it's available.

**Comment by yangky11** [comment]
Models pretrained on face-blurred images are now available for download [here](https://drive.google.com/drive/folders/1kr_IMocyg8hTSMWY_yzif4_tUVyHCiYU?usp=sharing).
